export const menu = [
  {
    id: "my-calendar",
    title: "My calendar",
    translate: "navigations.myCalendar",
    type: "item",
    icon: "calendar",
    url: "dashboard/admin/my-calendar",
    users: ["admin"],
  },
  {
    id: "my-clients",
    title: "My clients",
    translate: "navigations.myClients",
    type: "item",
    icon: "users",
    url: "dashboard/admin/my-clients",
    users: ["admin"],
  },
  // {
  //   id: "my-locations",
  //   title: "My locations",
  //   translate: "navigations.myLocations",
  //   type: "item",
  //   icon: "map-pin",
  //   url: "dashboard/admin/my-locations",
  //   users: ["superadmin"],
  // },
  // {
  //   id: "my-employees",
  //   title: "My employees",
  //   translate: "navigations.myEmployees",
  //   type: "item",
  //   icon: "user-check",
  //   url: "dashboard/admin/my-employees",
  //   users: ["superadmin"],
  // },

  {
    id: "my-services",
    title: "My services",
    translate: "navigations.myServices",
    type: "item",
    icon: "life-buoy",
    url: "dashboard/admin/my-services",
    users: ["admin"],
  },
  {
    id: "recommended",
    title: "Recommended",
    translate: "navigations.recommended",
    type: "item",
    icon: "gift",
    url: "dashboard/admin/recommended",
    users: ["admin"],
  },
  {
    id: "settings",
    title: "Settings",
    translate: "navigations.settings",
    type: "item",
    icon: "settings",
    url: "dashboard/admin/settings/booking-settings",
    users: ["admin"],
  },
  {
    id: "superadmin-all-users",
    title: "All users",
    translate: "navigations.allUsers",
    type: "item",
    icon: "user",
    url: "dashboard/superadmin/all-users",
    users: ["superadmin"],
  },
  {
    id: "sms-packages",
    title: "Sms packages",
    translate: "navigations.smsPackages",
    type: "item",
    icon: "package",
    url: "dashboard/superadmin/sms-packages",
    users: ["superadmin"],
  },
  {
    id: "gateway-country-prefix",
    title: "Gateway country prefix",
    translate: "navigations.gatewayCountryPrefix",
    type: "item",
    icon: "globe",
    url: "dashboard/superadmin/gateway-country-prefix",
    users: ["superadmin"],
  },
  {
    id: "licenses",
    title: "Licenses",
    translate: "navigations.licenses",
    type: "item",
    icon: "credit-card",
    url: "dashboard/superadmin/licenses",
    users: ["superadmin"],
  },
  {
    id: "all-voucher-partners",
    title: "all-voucher-partners",
    translate: "navigations.allVoucherPartners",
    type: "item",
    icon: "credit-card",
    url: "dashboard/superadmin/all-voucher-partners",
    users: ["superadmin"],
  },
];
