export const menu = [
  {
    id: "my-calendar",
    title: "My calendar",
    translate: "navigations.myCalendar",
    type: "item",
    icon: "calendar",
    url: "dashboard/admin/my-calendar",
  },
  {
    id: "my-clients",
    title: "My clients",
    translate: "navigations.myClients",
    type: "item",
    icon: "users",
    url: "dashboard/admin/my-clients",
  },
  {
    id: "my-locations",
    title: "My locations",
    translate: "navigations.myLocations",
    type: "item",
    icon: "map-pin",
    url: "dashboard/admin/my-locations",
    users: ["superadmin"],
  },
  {
    id: "my-employees",
    title: "My employees",
    translate: "navigations.myEmployees",
    type: "item",
    icon: "user-check",
    url: "dashboard/admin/my-employees",
    users: ["superadmin"],
  },
  {
    id: "my-services",
    title: "My services",
    translate: "navigations.myServices",
    type: "item",
    icon: "life-buoy",
    url: "dashboard/admin/my-services",
  },
  {
    id: "superadmin-all-users",
    title: "All users",
    translate: "navigations.allUsers",
    type: "item",
    icon: "user",
    url: "dashboard/superadmin/all-users",
    users: ["superadmin"],
  },
  {
    id: "home",
    title: "Home",
    translate: "navigations.home",
    type: "item",
    icon: "home",
    url: "home",
    users: ["superadmin"],
  },
  {
    id: "settings",
    title: "Settings",
    translate: "navigations.settings",
    type: "item",
    icon: "settings",
    url: "dashboard/admin/settings/worktime",
  },
  {
    id: "admin-settings",
    title: "Admin settings",
    translate: "navigations.adminSettings",
    type: "item",
    icon: "tool",
    url: "dashboard/admin/admin-settings/online-payment",
  },
];
