export const menu = [
  {
    id: "home",
    title: "Home",
    translate: "navigations.home",
    type: "item",
    icon: "home",
    url: "home",
  },
  {
    id: "settings",
    title: "Settings",
    translate: "navigations.settings",
    type: "item",
    icon: "settings",
    url: "dashboard/settings/worktime",
  },
  {
    id: "superadmin-all-users",
    title: "All users",
    translate: "navigations.allUsers",
    type: "item",
    icon: "user",
    url: "dashboard/superadmin/all-users",
    users: ["admin", "superadmin"],
  },
  {
    id: "my-locations",
    title: "My locations",
    translate: "navigations.myLocations",
    type: "item",
    icon: "map-pin",
    url: "dashboard/admin/my-locations",
    users: ["admin", "superadmin"],
  },
  {
    id: "my-services",
    title: "My services",
    translate: "navigations.myServices",
    type: "item",
    icon: "life-buoy",
    url: "dashboard/admin/my-services",
    users: ["admin", "superadmin"],
  },
];
