export const menu = [
  {
    id: "home",
    title: "Home",
    translate: "MENU.HOME",
    type: "item",
    icon: "home",
    url: "home",
  },
  {
    id: "settings",
    title: "Settings",
    translate: "Settings",
    type: "item",
    icon: "settings",
    url: "dashboard/settings/worktime",
  },
  {
    id: "superadmin-all-users",
    title: "All users",
    translate: "All users",
    type: "item",
    icon: "user",
    url: "dashboard/superadmin/all-users",
    users: ["admin", "superadmin"],
  },
  {
    id: "my-locations",
    title: "My locations",
    translate: "myLocations",
    type: "item",
    icon: "map-pin",
    url: "dashboard/admin/my-locations",
    users: ["admin", "superadmin"],
  },
];
