import { loadCldr, L10n } from "@syncfusion/ej2-base";
declare var require: any;

//#region English

loadCldr(
  require("cldr-data/supplemental/numberingSystems.json"),
  require("cldr-data/main/en/ca-gregorian.json"),
  require("cldr-data/main/en/numbers.json"),
  require("cldr-data/main/en/timeZoneNames.json")
);

//#endregion

//#region France
loadCldr(
  require("cldr-data/supplemental/numberingSystems.json"),
  require("cldr-data/main/fr/ca-gregorian.json"),
  require("cldr-data/main/fr/numbers.json"),
  require("cldr-data/main/fr/timeZoneNames.json")
);

L10n.load({
  fr: {
    schedule: {
      day: "Journée",
      week: "Semaine",
      workWeek: "Semaine de travail",
      month: "Mois",
      year: "An",
      agenda: "Ordre du jour",
      weekAgenda: "Agenda de la semaine",
      workWeekAgenda: "Agenda de la semaine de travail",
      monthAgenda: "Agenda du mois",
      today: "Aujourd'hui",
      noEvents: "Pas d'événements",
      emptyContainer: "Aucun événement n'est prévu ce jour-là.",
      allDay: "Toute la journée",
      start: "Début",
      end: "Fin",
      more: "plus",
      close: "Fermer",
      cancel: "Annuler",
      noTitle: "(Pas de titre)",
      delete: "Effacer",
      deleteEvent: "Supprimer l'événement",
      deleteMultipleEvent: "Supprimer plusieurs événements",
      selectedItems: "éléments sélectionnés",
      deleteSeries: "Supprimer la série",
      edit: "modifier",
      editSeries: "Modifier la série",
      editEvent: "Modifier l'événement",
      createEvent: "Créer",
      subject: "Assujettir",
      addTitle: "Ajouter un titre",
      moreDetails: "Plus de détails",
      save: "sauvegarder",
      editContent:
        "Voulez-vous modifier uniquement cet événement ou toute la série?",
      deleteContent: "Êtes-vous sûr de vouloir supprimer cet événement?",
      deleteMultipleContent:
        "Êtes-vous sûr de vouloir supprimer les événements sélectionnés?",
      newEvent: "Nouvel évènement",
      title: "Titre",
      location: "Emplacement",
      description: "La description",
      timezone: "Fuseau horaire",
      startTimezone: "Démarrer le fuseau horaire",
      endTimezone: "Fin du fuseau horaire",
      repeat: "Répéter",
      saveButton: "sauvegarder",
      cancelButton: "Annuler",
      deleteButton: "Effacer",
      recurrence: "Récurrence",
      wrongPattern: "Le modèle de récurrence n'est pas valide.",
      seriesChangeAlert:
        "Voulez-vous annuler les modifications apportées à des instances spécifiques de cette série et les associer à nouveau à l'ensemble de la série ?",
      createError:
        "La durée de l'événement doit être plus courte que sa fréquence. Raccourcissez la durée ou modifiez le modèle de récurrence dans l'éditeur d'événements de récurrence.",
      sameDayAlert:
        "Deux occurrences du même événement ne peuvent pas se produire le même jour.",
      occurenceAlert:
        "Impossible de replanifier une occurrence du rendez-vous périodique s'il ignore une occurrence ultérieure du même rendez-vous.",
      editRecurrence: "Modifier la récurrence",
      repeats: "Répétitions",
      alert: "Alerte",
      startEndError:
        "La date de fin sélectionnée se produit avant la date de début.",
      invalidDateError: "La valeur de date entrée n'est pas valide.",
      blockAlert:
        "Les événements ne peuvent pas être planifiés dans l'intervalle de temps bloqué.",
      ok: "D'accord",
      yes: "Oui",
      no: "Non",
      occurrence: "Occurrence",
      series: "Séries",
      previous: "précédent",
      next: "Prochain",
      timelineDay: "Jour de la chronologie",
      timelineWeek: "Semaine chronologique",
      timelineWorkWeek: "Semaine de travail",
      timelineMonth: "Mois de la chronologie",
      timelineYear: "Année de la chronologie",
      editFollowingEvent: "Événements suivants",
      deleteTitle: "Supprimer l'événement",
      editTitle: "Modifier l'événement",
      beginFrom: "Commencer à partir de",
      endAt: "Fin à",
      expandAllDaySection: "Développer la section toute la journée",
      collapseAllDaySection: "Réduire la section toute la journée",
      searchTimezone: "Recherche de fuseau horaire",
      noRecords: "Aucun enregistrement trouvé",
      deleteRecurrenceContent:
        "Voulez-vous supprimer uniquement cet événement ou toute la série?",
      recurrenceDateValidation:
        "Certains mois ont moins que la date sélectionnée. Pour ces mois, l'événement se produira à la dernière date du mois.",
    },
    recurrenceeditor: {
      none: "Aucun",
      daily: "du quotidien",
      weekly: "Hebdomadaire",
      monthly: "Mensuel",
      month: "Mois",
      yearly: "Annuel",
      never: "Jamais",
      until: "Jusqu'à",
      count: "Compter",
      first: "Premier",
      second: "Seconde",
      third: "Troisième",
      fourth: "Quatrième",
      last: "Dernier",
      repeat: "Répéter",
      repeatEvery: "Répétez chaque",
      on: "Répéter sur",
      end: "Fin",
      onDay: "journée",
      days: "journées",
      weeks: "semaines",
      months: "Mois",
      years: "Années",
      every: "chaque",
      summaryTimes: "fois",
      summaryOn: "sur",
      summaryUntil: "jusqu'à",
      summaryRepeat: "Répétitions",
      summaryDay: "journées",
      summaryWeek: "semaines",
      summaryMonth: "mois",
      summaryYear: "années",
      monthWeek: "Mois Semaine",
      monthPosition: "Position du mois",
      monthExpander: "Expander mois",
      yearExpander: "Expander année",
      repeatInterval: "Intervalle de répétition",
    },
    calendar: {
      today: "Aujourd'hui",
    },
  },
});

//#endregion

//#region Germany
loadCldr(
  require("cldr-data/supplemental/numberingSystems.json"),
  require("cldr-data/main/de/ca-gregorian.json"),
  require("cldr-data/main/de/numbers.json"),
  require("cldr-data/main/de/timeZoneNames.json")
);

L10n.load({
  de: {
    schedule: {
      day: "Tag",
      week: "Woche",
      workWeek: "Arbeitswoche",
      month: "Monat",
      year: "Jahr",
      agenda: "Agenda",
      weekAgenda: "Woche Agenda",
      workWeekAgenda: "Arbeitswoche Agenda",
      monthAgenda: "Monatsagenda",
      today: "Heute",
      noEvents: "Keine Ereignisse",
      emptyContainer: "An diesem Tag sind keine Veranstaltungen geplant.",
      allDay: "Den ganzen Tag",
      start: "Anfang",
      end: "Ende",
      more: "Mehr",
      close: "Schließen",
      cancel: "Stornieren",
      noTitle: "(Kein Titel)",
      delete: "Löschen",
      deleteEvent: "Ereignis löschen",
      deleteMultipleEvent: "Löschen Sie mehrere Ereignisse",
      selectedItems: "Artikel ausgewählt",
      deleteSeries: "Reihe löschen",
      edit: "Bearbeiten",
      editSeries: "Reihe bearbeiten",
      editEvent: "Veranstaltung bearbeiten",
      createEvent: "Erstellen",
      subject: "Gegenstand",
      addTitle: "Titel hinzufügen",
      moreDetails: "Mehr Details",
      save: "Speichern",
      editContent: "Wie möchten Sie den Termin in der Serie ändern?",
      deleteContent: "Möchten Sie dieses Ereignis wirklich löschen?",
      deleteMultipleContent:
        "Möchten Sie die ausgewählten Ereignisse wirklich löschen?",
      newEvent: "Neues Event",
      title: "Titel",
      location: "Ort",
      description: "Beschreibung",
      timezone: "Zeitzone",
      startTimezone: "Startzeitzone",
      endTimezone: "Endzeitzone",
      repeat: "Wiederholen",
      saveButton: "Speichern",
      cancelButton: "Stornieren",
      deleteButton: "Löschen",
      recurrence: "Wiederholung",
      wrongPattern: "Das Wiederholungsmuster ist nicht gültig.",
      seriesChangeAlert:
        "Möchten Sie die an bestimmten Instanzen dieser Serie vorgenommenen Änderungen verwerfen und erneut mit der gesamten Serie abgleichen?",
      createError:
        "Die Dauer des Ereignisses muss kürzer sein als die Häufigkeit des Ereignisses. Verkürzen Sie die Dauer oder ändern Sie das Wiederholungsmuster im Wiederholungsereignis-Editor.",
      sameDayAlert:
        "Zwei Vorkommen desselben Ereignisses können nicht am selben Tag auftreten.",
      occurenceAlert:
        "Ein Vorkommen des wiederkehrenden Termins kann nicht neu geplant werden, wenn ein späteres Vorkommen desselben Termins übersprungen wird.",
      editRecurrence: "Wiederholung bearbeiten",
      repeats: "Wiederholt",
      alert: "Aufmerksam",
      startEndError: "Das ausgewählte Enddatum liegt vor dem Startdatum.",
      invalidDateError: "Der eingegebene Datumswert ist ungültig.",
      blockAlert:
        "Ereignisse können nicht innerhalb des gesperrten Zeitbereichs geplant werden.",
      ok: "OK",
      yes: "Ja",
      no: "Nein",
      occurrence: "Auftreten",
      series: "Serie",
      previous: "Bisherige",
      next: "Nächster",
      timelineDay: "Timeline Tag",
      timelineWeek: "Timeline Woche",
      timelineWorkWeek: "Timeline-Arbeitswoche",
      timelineMonth: "Timeline-Monat",
      timelineYear: "Timeline-Jahr",
      editFollowingEvent: "Folge Veranstaltungen",
      deleteTitle: "Ereignis löschen",
      editTitle: "Ereignis bearbeiten",
      beginFrom: "Beginnen Sie von",
      endAt: "Ende um",
      expandAllDaySection: "Erweitern Sie den ganzen Tag",
      collapseAllDaySection: "Ganztägiger Zusammenbruch",
      searchTimezone: "Zeitzone suchen",
      noRecords: "Keine Aufzeichnungen gefunden",
      deleteRecurrenceContent:
        "Möchten Sie nur dieses Ereignis oder die ganze Serie löschen?",
      recurrenceDateValidation:
        "Einige Monate haben weniger als das ausgewählte Datum. In diesen Monaten fällt das Vorkommen auf das letzte Datum des Monats.",
    },
    recurrenceeditor: {
      none: "Keiner",
      daily: "Täglich",
      weekly: "Wöchentlich",
      monthly: "Monatlich",
      month: "Monat",
      yearly: "Jährlich",
      never: "noch nie",
      until: "Bis",
      count: "Anzahl",
      first: "Zuerst",
      second: "Zweite",
      third: "Dritte",
      fourth: "Vierte",
      last: "Letzte",
      repeat: "Wiederholen",
      repeatEvery: "Wiederhole jeden",
      on: "Wiederhole weiter",
      end: "Ende",
      onDay: "Tag",
      days: "Tage",
      weeks: "Wochen",
      months: "Monate",
      years: "Jahre",
      every: "jeden",
      summaryTimes: "mal",
      summaryOn: "auf",
      summaryUntil: "bis",
      summaryRepeat: "Wiederholt",
      summaryDay: "Tage",
      summaryWeek: "Wochen",
      summaryMonth: "Monate",
      summaryYear: "Jahre",
      monthWeek: "Monat Woche",
      monthPosition: "Monatliche Position",
      monthExpander: "Monats-Expander",
      yearExpander: "Jahres-Expander",
      repeatInterval: "Wiederholungsintervall",
    },
    calendar: {
      today: "Heute",
    },
  },
});

//#endregion

//#region Portugal
loadCldr(
  require("cldr-data/supplemental/numberingSystems.json"),
  require("cldr-data/main/pt/ca-gregorian.json"),
  require("cldr-data/main/pt/numbers.json"),
  require("cldr-data/main/pt/timeZoneNames.json")
);

L10n.load({
  pt: {
    schedule: {
      day: "Dia",
      week: "Semana",
      workWeek: "Semana de trabalho",
      month: "Mês",
      year: "Ano",
      agenda: "Agenda",
      weekAgenda: "Agenda da semana",
      workWeekAgenda: "Agenda da Semana de Trabalho",
      monthAgenda: "Agenda do mês",
      today: "Hoje",
      noEvents: "Sem eventos",
      emptyContainer: "Não há eventos agendados para este dia.",
      allDay: "Dia todo",
      start: "Começar",
      end: "Fim",
      more: "Mais",
      close: "Fechar",
      cancel: "Cancelar",
      noTitle: "(Sem título)",
      delete: "Excluir",
      deleteEvent: "Este evento",
      deleteMultipleEvent: "Excluir vários eventos",
      selectedItems: "Itens selecionados",
      deleteSeries: "Série inteira",
      edit: "Editar",
      editSeries: "Série inteira",
      editEvent: "Este evento",
      createEvent: "Crio",
      subject: "Sujeito",
      addTitle: "Adicionar título",
      moreDetails: "Mais detalhes",
      save: "Salve ",
      editContent: "Você gostaria de mudar o compromisso da série?",
      deleteContent: "Tem certeza de que deseja excluir este evento?",
      deleteMultipleContent:
        "Tem certeza de que deseja excluir os eventos selecionados?",
      newEvent: "Novo evento",
      title: "Título",
      location: "Localização",
      description: "Descrição",
      timezone: "Fuso horário",
      startTimezone: "Iniciar fuso horário",
      endTimezone: "Fuso horário final",
      repeat: "Repetir",
      saveButton: "Salve ",
      cancelButton: "Cancelar",
      deleteButton: "Excluir",
      recurrence: "Recorrência",
      wrongPattern: "O padrão de recorrência não é válido.",
      seriesChangeAlert:
        "Deseja cancelar as alterações feitas em instâncias específicas desta série e associá-las à série inteira novamente?",
      createError:
        "A duração do evento deve ser menor que a frequência com que ele ocorre. Diminua a duração ou altere o padrão de recorrência no editor de eventos de recorrência.",
      sameDayAlert:
        "Duas ocorrências do mesmo evento não podem ocorrer no mesmo dia.",
      occurenceAlert:
        "Não é possível reagendar uma ocorrência do compromisso recorrente se ele ignorar uma ocorrência posterior do mesmo compromisso.",
      editRecurrence: "Editar recorrência",
      repeats: "Repete",
      alert: "Alerta",
      startEndError: "A data final selecionada ocorre antes da data de início.",
      invalidDateError: "O valor da data inserida é inválido.",
      blockAlert:
        "Os eventos não podem ser agendados dentro do intervalo de tempo bloqueado.",
      ok: "Está bem",
      yes: "sim",
      no: "Não",
      occurrence: "Ocorrência",
      series: "Series",
      previous: "Anterior",
      next: "Próximo",
      timelineDay: "Dia da linha do tempo",
      timelineWeek: "Semana da Linha do Tempo",
      timelineWorkWeek: "Semana de trabalho da linha do tempo",
      timelineMonth: "Mês da linha do tempo",
      timelineYear: "Ano da Linha do Tempo",
      editFollowingEvent: "Eventos seguintes",
      deleteTitle: "Excluir evento",
      editTitle: "Editar evento",
      beginFrom: "Começar de",
      endAt: "Termina em",
      expandAllDaySection: "Seção de expansão para o dia todo",
      collapseAllDaySection: "Recolher a seção do dia inteiro",
      searchTimezone: "Pesquisar fuso horário",
      noRecords: "Nenhum registro foi encontrado",
    },
    recurrenceeditor: {
      none: "Nenhum",
      daily: "Diariamente",
      weekly: "Semanal",
      monthly: "Por mês",
      month: "Mês",
      yearly: "Anual",
      never: "Nunca",
      until: "Até",
      count: "Contagem",
      first: "Primeiro",
      second: "Segundo",
      third: "Terceiro",
      fourth: "Quarto",
      last: "Último",
      repeat: "Repetir",
      repeatEvery: "Repita cada",
      on: "Repetir em",
      end: "Fim",
      onDay: "Dia",
      days: "Dias)",
      weeks: "Semana (s)",
      months: "Mês (es)",
      years: "Anos)",
      every: "cada",
      summaryTimes: "tempo (s)",
      summaryOn: "em",
      summaryUntil: "até",
      summaryRepeat: "Repete",
      summaryDay: "dias)",
      summaryWeek: "semana (s)",
      summaryMonth: "mês (es)",
      summaryYear: "anos)",
      monthWeek: "Mês Semana",
      monthPosition: "Posição do mês",
      monthExpander: "Expansor do mês",
      yearExpander: "Expansor do ano",
      repeatInterval: "Intervalo de repetição",
    },
    calendar: {
      today: "Hoje",
    },
  },
});
//#endregion

//#region Serbian
loadCldr(
  require("cldr-data/supplemental/numberingSystems.json"),
  require("cldr-data/main/sr-Latn/ca-gregorian.json"),
  require("cldr-data/main/sr-Latn/numbers.json"),
  require("cldr-data/main/sr-Latn/timeZoneNames.json")
);

L10n.load({
  "sr-Latn": {
    schedule: {
      day: "Dan",
      week: "Cela nedelja",
      workWeek: "Radna nedelja",
      month: "Mesec",
      year: "Godina",
      agenda: "dnevni red",
      weekAgenda: "Nedeljni dnevni red",
      workWeekAgenda: "Agenda radne nedelje",
      monthAgenda: "Mesečna agenda",
      today: "Danas",
      noEvents: "Nema događaja",
      emptyContainer: "Za ovaj dan nema zakazanih događaja.",
      allDay: "Celi dan",
      start: "Početak",
      end: "Kraj",
      more: "više",
      close: "Zatvoriti",
      cancel: "Otkazati",
      noTitle: "(Bez naslova)",
      delete: "Izbrisati",
      deleteEvent: "Detalji termina",
      deleteMultipleEvent: "Brisanje više događaja",
      selectedItems: "Odabrane stavke",
      deleteSeries: "Cela serija",
      edit: "Uredi",
      editSeries: "Cela serija",
      editEvent: "Detalji termina",
      createEvent: "Kreirati",
      subject: "predmet",
      addTitle: "Dodaj Naslov",
      moreDetails: "Više detalja",
      save: "Sačuvati",
      editContent: "Kako biste želeli promeniti termin u seriji?",
      deleteContent: "Jeste li sigurni da želite izbrisati ovaj događaj?",
      deleteMultipleContent:
        "Jeste li sigurni da želite izbrisati odabrane događaje?",
      newEvent: "Novi događaj",
      title: "Naslov",
      location: "Mesto",
      description: "Opis",
      timezone: "Vremenska zona",
      startTimezone: "Pokrenite vremensku zonu",
      endTimezone: "Kraj vremenske zone",
      repeat: "Ponoviti",
      saveButton: "Sačuvaj",
      cancelButton: "Otkaži",
      deleteButton: "Obriši",
      recurrence: "vraćanje",
      wrongPattern: "Obrazac recidiva nije valjan.",
      seriesChangeAlert:
        "Želite li otkazati promene učinjene na određenim primercima ove serije i ponovno ih uskladiti s celom serijom?",
      createError:
        "Trajanje događaja mora biti kraće od onog koliko često se događaj događa. Skratite trajanje ili promenite obrazac ponavljanja u uređivaču događaja ponavljanja.",
      sameDayAlert:
        "Dve pojave istog događaja ne mogu se dogoditi istog dana.",
      occurenceAlert:
        "Ne može se zakazati pojava ponavljajućeg sastanka ako preskoči kasniju pojavu istog sastanka.",
      editRecurrence: "Uređivanje ponavljanja",
      repeats: "ponavlja",
      alert: "uzbuna",
      startEndError: "Odabrani datum završetka događa je pre početka događaja.",
      invalidDateError: "Unesena vrijednost datuma nije važeća.",
      blockAlert:
        "Događaji se ne mogu zakazati unutar blokiranog vremenskog raspona.",
      ok: "U redu",
      yes: "Da",
      no: "Ne",
      occurrence: "događaj",
      series: "Niz",
      previous: "prethodni",
      next: "Sljedeći",
      timelineDay: "Dan vremenske trake",
      timelineWeek: "Nedelja vremenske trake",
      timelineWorkWeek: "Radna nedelja vremenske linije",
      timelineMonth: "Mesec vremena",
      timelineYear: "Vremenska linija",
      editFollowingEvent: "Sledite događaje",
      deleteTitle: "Izbriši događaj",
      editTitle: "Uređivanje događaja",
      beginFrom: "Počnite od",
      endAt: "Kraj",
      expandAllDaySection: "Proširi-celodnevni odjeljak",
      collapseAllDaySection: "Sakupi celodnevni odjeljak",
      searchTimezone: "Traži vremensku zonu",
      noRecords: "Nije pronađen nijedan zapis",
    },
    recurrenceeditor: {
      none: "nijedan",
      daily: "Dnevno",
      weekly: "Nedeljno",
      monthly: "Mesečno",
      month: "Mesec",
      yearly: "Godišnje",
      never: "Nikada",
      until: "Do",
      count: "Računati",
      first: "Prvi",
      second: "Drugi",
      third: "treći",
      fourth: "Četvrta",
      last: "Posljednji",
      repeat: "Ponoviti",
      repeatEvery: "Ponovite svaki",
      on: "Ponovite Uključeno",
      end: "Kraj",
      onDay: "Dan",
      days: "Dan (a)",
      weeks: "Nedeljni",
      months: "Mesec (i)",
      years: "Godine)",
      every: "svaki",
      summaryTimes: "Vreme (s)",
      summaryOn: "na",
      summaryUntil: "do",
      summaryRepeat: "ponavlja",
      summaryDay: "dan (a)",
      summaryWeek: "dnevni)",
      summaryMonth: "mesec (i)",
      summaryYear: "godine)",
      monthWeek: "Mesečna nedelja",
      monthPosition: "Mesečna pozicija",
      monthExpander: "Mesečni ekspander",
      yearExpander: "Godine Expander",
      repeatInterval: "Interval ponovite",
    },
    calendar: {
        today: "Danas"
    }
  },
});

//#endregion

export class DefaultCalendarLanguages {
  constructor() {}
}
